import { QRPayloadParsed, SocietyEvent, ScanVerificationResult, GateCheckInRecord } from '../types';

/**
 * Normalizes a house/flat number for reliable matching:
 * - Trims whitespace
 * - Converts to uppercase
 * - Normalizes separators (e.g. "a 101" -> "A-101", "b102" -> "B-102")
 */
export function normalizeHouseNo(input: string): string {
  if (!input) return '';
  const trimmed = input.trim();
  // Extract purely numeric digits if present (e.g. "A-102" -> "102", " 102 " -> "102")
  const digitsMatch = trimmed.match(/\d+/);
  if (digitsMatch) {
    const num = parseInt(digitsMatch[0], 10);
    if (!isNaN(num)) {
      return num.toString();
    }
  }
  return trimmed;
}

/**
 * Formats the standard QR Data Payload according to specifications:
 * [EVENT_CODE]|HOUSE:[HOUSE_NO]|NAME:[NAME]|MEMBERS:[COUNT]|SWAMI:[SWAMI_COUNT]|FOOD:[FOOD_PREF]
 */
export function generateQRPayload(
  eventCode: string,
  houseNo: string,
  name: string,
  members: number,
  swaminarayanCount: number = 0,
  foodPreference: 'regular' | 'swaminarayan_jain' = 'regular'
): string {
  const cleanCode = eventCode.trim().toUpperCase();
  const cleanHouse = normalizeHouseNo(houseNo);
  const cleanName = name.trim().replace(/[|]/g, ' '); // avoid delimiter injection
  const memberCount = Math.max(1, Math.floor(members || 1));
  const swamiCount = Math.max(0, Math.min(memberCount, Math.floor(swaminarayanCount || 0)));
  const foodPref = foodPreference === 'swaminarayan_jain' || swamiCount > 0 ? 'swaminarayan_jain' : 'regular';

  let payload = `${cleanCode}|HOUSE:${cleanHouse}|NAME:${cleanName}|MEMBERS:${memberCount}`;
  if (swamiCount > 0 || foodPref === 'swaminarayan_jain') {
    payload += `|SWAMI:${swamiCount}|FOOD:${foodPref}`;
  }

  return payload;
}

/**
 * Parses QR payload format:
 * [EVENT_CODE]|HOUSE:[HOUSE_NO]|NAME:[NAME]|MEMBERS:[COUNT]|SWAMI:[SWAMI_COUNT]|FOOD:[FOOD_PREF]
 */
export function parseQRPayload(payload: string): QRPayloadParsed | null {
  if (!payload || typeof payload !== 'string') return null;

  const parts = payload.trim().split('|');
  if (parts.length < 4) return null;

  const eventCode = parts[0].trim();
  let houseNo = '';
  let residentName = '';
  let memberCount = 1;
  let foodPreference: 'regular' | 'swaminarayan_jain' = 'regular';
  let swaminarayanCount = 0;

  for (let i = 1; i < parts.length; i++) {
    const part = parts[i].trim();
    if (part.startsWith('HOUSE:')) {
      houseNo = normalizeHouseNo(part.replace('HOUSE:', ''));
    } else if (part.startsWith('NAME:')) {
      residentName = part.replace('NAME:', '').trim();
    } else if (part.startsWith('MEMBERS:')) {
      const parsedMembers = parseInt(part.replace('MEMBERS:', '').trim(), 10);
      if (!isNaN(parsedMembers) && parsedMembers > 0) {
        memberCount = parsedMembers;
      }
    } else if (part.startsWith('SWAMI:')) {
      const parsedSwami = parseInt(part.replace('SWAMI:', '').trim(), 10);
      if (!isNaN(parsedSwami) && parsedSwami >= 0) {
        swaminarayanCount = parsedSwami;
      }
    } else if (part.startsWith('FOOD:')) {
      const parsedFood = part.replace('FOOD:', '').trim().toLowerCase();
      if (parsedFood === 'swaminarayan_jain' || parsedFood === 'regular') {
        foodPreference = parsedFood;
      }
    }
  }

  if (swaminarayanCount > 0) {
    foodPreference = 'swaminarayan_jain';
  }

  if (!eventCode || !houseNo || !residentName) {
    return null;
  }

  return {
    eventCode,
    houseNo,
    residentName,
    memberCount,
    foodPreference,
    swaminarayanCount,
  };
}

/**
 * Validates a scanned QR payload against the active event and check-in history
 */
export function verifyScannedPayload(
  rawPayload: string,
  activeEvent: SocietyEvent,
  allEvents: SocietyEvent[],
  existingCheckIns: GateCheckInRecord[]
): ScanVerificationResult {
  const parsed = parseQRPayload(rawPayload);

  if (!parsed) {
    return {
      status: 'invalid',
      title: 'INVALID QR FORMAT',
      message: 'Scanned QR code does not conform to the society event pass standard or was generated by an external source.',
      rawText: rawPayload,
    };
  }

  // Check event code match
  const activeCode = activeEvent.eventCode.trim().toUpperCase();
  const scannedCode = parsed.eventCode.trim().toUpperCase();

  if (scannedCode !== activeCode) {
    // Check if it belongs to another event in the society
    const otherEvent = allEvents.find(
      (e) => e.eventCode.trim().toUpperCase() === scannedCode
    );

    if (otherEvent) {
      return {
        status: 'invalid',
        title: 'WRONG EVENT PASS',
        message: `This pass is for "${otherEvent.name}" (${otherEvent.eventCode}), but the active gate is for "${activeEvent.name}".`,
        parsed,
        rawText: rawPayload,
      };
    }

    return {
      status: 'invalid',
      title: 'EVENT CODE MISMATCH',
      message: `Invalid event code "${scannedCode}". Expected "${activeCode}" for this gate.`,
      parsed,
      rawText: rawPayload,
    };
  }

  // Check if house number is in the pre-approved paid house list
  const normalizedHouse = normalizeHouseNo(parsed.houseNo);
  const normalizedPaidList = activeEvent.paidHouses.map((h) => normalizeHouseNo(h));

  const isPaid = normalizedPaidList.includes(normalizedHouse);
  if (!isPaid) {
    return {
      status: 'invalid',
      title: 'HOUSE PAYMENT NOT VERIFIED',
      message: `Payment is not in the verified list for House [${parsed.houseNo}]. Please ask resident to verify with Festival Committee.`,
      parsed,
      matchedEvent: activeEvent,
      rawText: rawPayload,
    };
  }

  // Find any previous approved check-ins for this house in the active event
  const previousEntries = existingCheckIns.filter(
    (c) =>
      c.eventId === activeEvent.id &&
      normalizeHouseNo(c.houseNo) === normalizedHouse &&
      c.status === 'approved'
  );

  const totalRegistered = Math.max(1, parsed.memberCount || 1);
  const alreadyEntered = previousEntries.reduce((sum, c) => sum + (c.memberCount || 1), 0);
  const remaining = Math.max(0, totalRegistered - alreadyEntered);

  // If ALL members have already entered
  if (remaining <= 0) {
    const lastCheckIn = previousEntries[0];
    return {
      status: 'duplicate',
      title: 'ALL MEMBERS ALREADY ENTERED',
      message: `All ${totalRegistered} registered members for House ${parsed.houseNo} (${parsed.residentName}) have already entered.`,
      parsed,
      matchedEvent: activeEvent,
      previousCheckIn: lastCheckIn,
      previousEntries,
      totalRegistered,
      alreadyEntered,
      remaining: 0,
      rawText: rawPayload,
    };
  }

  // If partial entry (some have already entered, some remain)
  if (alreadyEntered > 0) {
    return {
      status: 'approved',
      title: `PARTIAL ENTRY (${remaining} LEFT)`,
      message: `House ${parsed.houseNo}: ${alreadyEntered} already entered, ${remaining} member${remaining > 1 ? 's' : ''} left outside.`,
      parsed,
      matchedEvent: activeEvent,
      previousCheckIn: previousEntries[0],
      previousEntries,
      totalRegistered,
      alreadyEntered,
      remaining,
      rawText: rawPayload,
    };
  }

  // First check-in for this house
  return {
    status: 'approved',
    title: 'ENTRY APPROVED',
    message: `Verified resident of House ${parsed.houseNo}. ${totalRegistered} family member${totalRegistered > 1 ? 's' : ''} eligible.`,
    parsed,
    matchedEvent: activeEvent,
    totalRegistered,
    alreadyEntered: 0,
    remaining: totalRegistered,
    rawText: rawPayload,
  };
}
